# Generated by Django 4.2.3 on 2023-07-26 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=127, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("description", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateField()),
                ("stock_quantity", models.PositiveIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="author_books", to="book.author"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="author",
            constraint=models.CheckConstraint(
                check=models.Q(("name__isnull", False), ("user__isnull", False), _connector="OR"),
                name="provide_at_least_name_or_user",
                violation_error_message="provide either of name or user at least",
            ),
        ),
    ]
