# Generated by Django 4.2.3 on 2023-07-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0001_initial_order_and_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(choices=[("OP", "open"), ("PE", "pending"), ("DO", "done")], max_length=4),
        ),
    ]
